import { Terminal, Code2, Network, Sparkles, Layers } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Landing() {
  return (
    <div className="min-h-screen bg-background text-text-primary font-sans overflow-x-hidden selection:bg-accent/30">
      {/* Navbar */}
      <nav className="fixed top-0 w-full border-b border-border bg-background/80 backdrop-blur-md z-50 flex items-center justify-between px-6 py-4">
        <div className="flex items-center gap-2">
          <Terminal size={20} className="text-accent" />
          <span className="font-bold tracking-tighter text-accent text-xl">VANARSENA</span>
</div>
        <div className="flex items-center gap-6">
          <a href="#" className="text-sm font-medium hover:text-accent transition-colors duration-150">LOGIN</a>
          <div className="px-2 py-1 rounded bg-surface border border-border text-xs font-mono text-text-secondary">
            v1.0.4-stable
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="min-h-screen flex flex-col items-center justify-center px-4 pt-20 pb-10 text-center relative">
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight max-w-4xl leading-tight text-text-primary">
          Map Your Codebase,<br />Master Your Architecture
        </h1>
        <p className="mt-6 text-xl text-text-secondary max-w-2xl">
          A high-density visual intelligence platform for complex software systems. 
          Ingest, analyze, and navigate multi-repo architectures with surgical precision.
        </p>
        <div className="mt-10 flex items-center gap-4">
          <Link 
            to="/onboarding" 
            className="px-6 py-3 bg-accent text-white rounded font-medium hover:bg-accent/90 transition-colors duration-150 shadow-[0_4px_20px_rgba(99,102,241,0.3)]"
          >
            Get Started for Free
          </Link>
          <a 
            href="#" 
            className="px-6 py-3 border border-border text-text-primary py-3 rounded font-medium hover:bg-surface transition-colors duration-150"
          >
            View Demo
          </a>
        </div>
        
        {/* Decorative Grid Line in Hero */}
        <div className="absolute bottom-0 w-full h-[1px] bg-border opacity-50" />
      </section>

      {/* Process Section */}
      <section className="py-24 px-6 max-w-7xl mx-auto">
        <div className="mb-16">
          <div className="text-xs font-mono text-accent mb-2 tracking-wider">PROCESS</div>
          <h2 className="text-3xl font-bold">Automated Synthesis</h2>
        </div>
        
        <div className="grid md:grid-cols-3 gap-6">
          {[
            { step: '01', title: 'Ingest URL', desc: 'Pull code from GitHub, GitLab, or Bitbucket repository. Our agents securely clone and prepare the environment for deep scanning.' },
            { step: '02', title: 'AST Parsing', desc: 'Our multi-language parser generates Abstract Syntax Trees to map every function, class, and dependency within the codebase.' },
            { step: '03', title: 'Visual Synthesis', desc: 'Complex relationships are translated into navigable 2D graphs, providing instant clarity on your architectural integrity.' },
          ].map((item, idx) => (
            <div key={idx} className="bg-surface border border-border p-8 rounded-md flex flex-col items-start hover:border-accent/40 transition-colors duration-250">
              <div className="font-mono text-xl text-text-secondary mb-4">{item.step}.</div>
              <h3 className="text-xl font-semibold mb-3 font-mono text-mono">{item.title}</h3>
              <p className="text-text-secondary leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Capabilities Section */}
      <section className="py-24 px-6 max-w-7xl mx-auto border-t border-border/50">
        <div className="mb-16">
          <div className="text-xs font-mono text-accent mb-2 tracking-wider">CAPABILITIES</div>
          <h2 className="text-3xl font-bold">Engineered for Complexity</h2>
        </div>
        
        <div className="grid md:grid-cols-2 gap-6">
          {[
            { icon: Network, title: 'Interactive Graphs', desc: 'Fly through your codebase. Click any node to see exact definitions, references, and circular dependencies in real-time.' },
            { icon: Sparkles, title: 'AI Summaries', desc: 'Get instant contextual summaries of directory purposes, complex logic blocks, and onboarding guides generated by context-aware LLMs.' },
            { icon: Code2, title: 'Impact Analysis', desc: 'Predict the ripple effect of a code change before you commit. Identify potential breaking points in downstream services.' },
            { icon: Layers, title: 'Multi-Repo Intelligence', desc: 'Connect related repositories to visualize the entire microservice ecosystem. Map API contracts and events driven flows across boundaries.' },
          ].map((item, idx) => (
            <div key={idx} className="bg-surface-flat border border-border p-8 flex flex-col gap-4 rounded-md">
              <item.icon size={24} className="text-accent" />
              <h3 className="text-xl font-bold">{item.title}</h3>
              <p className="text-text-secondary">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Deep CTA Banner */}
      <section className="py-32 px-6 text-center border-t border-border">
        <h2 className="text-4xl font-bold mb-8">Ready to audit your architecture?</h2>
        <Link 
          to="/onboarding" 
          className="px-8 py-4 bg-accent text-white rounded font-medium text-lg hover:bg-accent/90 transition-colors duration-150 shadow-[0_4px_25px_rgba(99,102,241,0.4)]"
        >
          Get Started for Free
        </Link>
      </section>

      {/* Footer */}
      <footer className="border-t border-border bg-surface-flat py-8 px-6 flex flex-col md:flex-row items-center justify-between text-sm text-text-secondary font-mono">
        <div>© 2024 Repository Navigator. All rights reserved.</div>
        <div className="flex items-center gap-6 mt-4 md:mt-0">
          <a href="#" className="hover:text-text-primary transition-colors">Docs</a>
          <a href="#" className="hover:text-text-primary transition-colors">API</a>
          <a href="#" className="hover:text-text-primary transition-colors">Status</a>
          <a href="#" className="hover:text-text-primary transition-colors">Privacy</a>
        </div>
      </footer>
    </div>
  );
}
